import pickle

import pytest

import openai

EXCEPTION_TEST_CASES = [
    openai.InvalidRequestError(
        "message",
        "param",
        code=400,
        http_body={"test": "test1"},
        http_status="fail",
        json_body={"text": "iono some text"},
        headers={"request-id": "asasd"},
    ),
    openai.AuthenticationError(),
    openai.PermissionError(),
    openai.RateLimitError(),
    openai.ServiceUnavailableError(),
    openai.SignatureVerificationError("message", "sig_header?"),
    openai.APIConnectionError("message!", should_retry=True),
    openai.TryAgain(),
    openai.Timeout(),
    openai.APIError(
        message="message",
        code=400,
        http_body={"test": "test1"},
        http_status="fail",
        json_body={"text": "iono some text"},
        headers={"request-id": "asasd"},
    ),
    openai.OpenAIError(),
]


class TestExceptions:
    @pytest.mark.parametrize("error", EXCEPTION_TEST_CASES)
    def test_exceptions_are_pickleable(self, error) -> None:
        assert error.__repr__() == pickle.loads(pickle.dumps(error)).__repr__()
